name: voicense_frontend
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.22
  record: ^5.0.5
  path_provider: ^2.1.3
  http: ^1.2.1
  flutter_bloc: ^8.1.5
  intl: ^0.18.1
  flutter_tts: ^3.8.5
  awesome_dialog: ^3.2.1
  shared_preferences: ^2.2.3
  lottie: ^3.1.2
  dio: ^5.5.0+1
  open_file: ^3.3.2


dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  device_preview: ^1.1.0
  permission_handler: ^11.3.1
  equatable: ^2.0.5
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/app_icon.png"
    min_sdk_android: 23 # android min sdk min:16, default 21
    web:
      generate: true
      image_path: "assets/app_icon.png"
      background_color: "#hexcode"
      theme_color: "#hexcode"
    windows:
      generate: true
      image_path: "assets/app_icon.png"
      icon_size: 48 # min:48, max:256, default: 48
    macos:
      generate: true
      image_path: "assets/app_icon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/lecture_notes.md
    - assets/voicense_logo.png
    - assets/loading_animation.json
    - assets/profile-pic.jpg
    - assets/background_splash.png
    - assets/done.png
